### ISSUE TITLE
ERROR: connect ECONNREFUSED 127.0.0.1:4444

### ISSUE THREAD

**Issue by tryenc** [poorgeek/tenon-selenium-example#1]
First off, I'm extremely grateful for all the tooling and examples that you've provided for the Tenon API. You're an amazing resource.

I'm having trouble running this repo. I've followed all the instructions, but when I run `grunt webdriver`, I get the following error in my terminal.

```
Running "webdriver:test" (webdriver) task

ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
Error: connect ECONNREFUSED 127.0.0.1:4444

Warning: Task "webdriver:test" failed. Use --force to continue.

Aborted due to warnings.
```
I tried running this with the force flag, `--force`, but I ended up with the same errors.

In Gruntfile.js, I tried upgrading the `grunt.initConfig.selenium_standalone.server.seleniumVersion` to 3.4.0 and `grunt.initConfig.selenium_standalone.server.drivers.chrome.version` to 2.31, but this didn't seem to make any difference.

**Comment by poorgeek** [comment]
@tryenc You're getting that error because you need to start the selenium standalone server. For demo purposes the default task in the Gruntfile.js will start the server, run the tests, and stop the server.

Just to be sure that this is what was happening, I did update the selenium and chrome driver libraries to the latest version and everything works as expected.

Let me know if that doesn't solve your problem or if you have any other questions.

**Comment by karlgroves** [comment]
@poorgeek I have successfully replicated the problem.

output is:

```
export TENON_API_KEY=XYZPDQREDACTED && grunt          
Running "selenium_standalone:server:install" (selenium_standalone) task

Running "selenium_standalone:server:start" (selenium_standalone) task

Running "webdriver:test" (webdriver) task

ERROR: Connection refused
chrome
Error: Connection refused

>> 
Warning: Task "webdriver:test" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by tryenc** [comment]
I actually was able to get this to work by simply running `grunt`, which I believe is because the tasks to install the standalone server, start the server, and run the tests are all defined as 'default'.
```
grunt.registerTask('default', [
    'selenium_standalone:server:install',
    'selenium_standalone:server:start',
    'webdriver:test',
    'selenium_standalone:server:stop'
]);
```
I think it may also be a little confusing because the tests that you have set up are failing, not because of your code, but due to accessibility errors on Google's homepage. The failing tests are resulting in 'Warning: Task "webdriver:test" failed', which makes it sound like there was a local error.

The google.com test suite resulted in five errors including, "Page has no headings", "This form element has no label", and "This link has no text inside it".
The Google Settings Menu suite resulted in two errors.

**Comment by tryenc** [comment]
Maybe change `grunt webdriver` to simply `grunt`

**Comment by poorgeek** [comment]
Ah. Good catch @tryenc. I've updated the README so that it a) tells you to run the right grunt command b) tells you what the expected results *should* be.

**Comment by poorgeek** [comment]
Closing until there are further comments.
